//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace TEST.WS_Ecuador {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="IntegracionSoap", Namespace="http://tempuri.org/")]
    public partial class Integracion : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback FacturaOperationCompleted;
        
        private System.Threading.SendOrPostCallback LOTEOperationCompleted;
        
        private System.Threading.SendOrPostCallback TimbresRestantesOperationCompleted;
        
        private System.Threading.SendOrPostCallback DescargaFacturaXMLOperationCompleted;
        
        private System.Threading.SendOrPostCallback DescargaFacturaPDFOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidaUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback EstatusDocumentoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Integracion() {
            this.Url = global::TEST.Properties.Settings.Default.TEST_WS_Ecuador_Integracion;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event FacturaCompletedEventHandler FacturaCompleted;
        
        /// <remarks/>
        public event LOTECompletedEventHandler LOTECompleted;
        
        /// <remarks/>
        public event TimbresRestantesCompletedEventHandler TimbresRestantesCompleted;
        
        /// <remarks/>
        public event DescargaFacturaXMLCompletedEventHandler DescargaFacturaXMLCompleted;
        
        /// <remarks/>
        public event DescargaFacturaPDFCompletedEventHandler DescargaFacturaPDFCompleted;
        
        /// <remarks/>
        public event ValidaUsuarioCompletedEventHandler ValidaUsuarioCompleted;
        
        /// <remarks/>
        public event EstatusDocumentoCompletedEventHandler EstatusDocumentoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Factura", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RespuestaTimbradoTXT Factura(string ruc, string user, string userPassword, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] ContenidoArchivoTexto, string NombreArchivo) {
            object[] results = this.Invoke("Factura", new object[] {
                        ruc,
                        user,
                        userPassword,
                        ContenidoArchivoTexto,
                        NombreArchivo});
            return ((RespuestaTimbradoTXT)(results[0]));
        }
        
        /// <remarks/>
        public void FacturaAsync(string ruc, string user, string userPassword, byte[] ContenidoArchivoTexto, string NombreArchivo) {
            this.FacturaAsync(ruc, user, userPassword, ContenidoArchivoTexto, NombreArchivo, null);
        }
        
        /// <remarks/>
        public void FacturaAsync(string ruc, string user, string userPassword, byte[] ContenidoArchivoTexto, string NombreArchivo, object userState) {
            if ((this.FacturaOperationCompleted == null)) {
                this.FacturaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFacturaOperationCompleted);
            }
            this.InvokeAsync("Factura", new object[] {
                        ruc,
                        user,
                        userPassword,
                        ContenidoArchivoTexto,
                        NombreArchivo}, this.FacturaOperationCompleted, userState);
        }
        
        private void OnFacturaOperationCompleted(object arg) {
            if ((this.FacturaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FacturaCompleted(this, new FacturaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LOTE", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RespLoteIntegracion LOTE(string ruc, string user, string userPassword, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] ContenidoArchivoTexto, string NombreArchivo) {
            object[] results = this.Invoke("LOTE", new object[] {
                        ruc,
                        user,
                        userPassword,
                        ContenidoArchivoTexto,
                        NombreArchivo});
            return ((RespLoteIntegracion)(results[0]));
        }
        
        /// <remarks/>
        public void LOTEAsync(string ruc, string user, string userPassword, byte[] ContenidoArchivoTexto, string NombreArchivo) {
            this.LOTEAsync(ruc, user, userPassword, ContenidoArchivoTexto, NombreArchivo, null);
        }
        
        /// <remarks/>
        public void LOTEAsync(string ruc, string user, string userPassword, byte[] ContenidoArchivoTexto, string NombreArchivo, object userState) {
            if ((this.LOTEOperationCompleted == null)) {
                this.LOTEOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLOTEOperationCompleted);
            }
            this.InvokeAsync("LOTE", new object[] {
                        ruc,
                        user,
                        userPassword,
                        ContenidoArchivoTexto,
                        NombreArchivo}, this.LOTEOperationCompleted, userState);
        }
        
        private void OnLOTEOperationCompleted(object arg) {
            if ((this.LOTECompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LOTECompleted(this, new LOTECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TimbresRestantes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Timbresrestantes TimbresRestantes(string user, string userPassword, string RUCEmisor) {
            object[] results = this.Invoke("TimbresRestantes", new object[] {
                        user,
                        userPassword,
                        RUCEmisor});
            return ((Timbresrestantes)(results[0]));
        }
        
        /// <remarks/>
        public void TimbresRestantesAsync(string user, string userPassword, string RUCEmisor) {
            this.TimbresRestantesAsync(user, userPassword, RUCEmisor, null);
        }
        
        /// <remarks/>
        public void TimbresRestantesAsync(string user, string userPassword, string RUCEmisor, object userState) {
            if ((this.TimbresRestantesOperationCompleted == null)) {
                this.TimbresRestantesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTimbresRestantesOperationCompleted);
            }
            this.InvokeAsync("TimbresRestantes", new object[] {
                        user,
                        userPassword,
                        RUCEmisor}, this.TimbresRestantesOperationCompleted, userState);
        }
        
        private void OnTimbresRestantesOperationCompleted(object arg) {
            if ((this.TimbresRestantesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TimbresRestantesCompleted(this, new TimbresRestantesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DescargaFacturaXML", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DescargaDocumentoXML DescargaFacturaXML(string ruc, string user, string password, string documento) {
            object[] results = this.Invoke("DescargaFacturaXML", new object[] {
                        ruc,
                        user,
                        password,
                        documento});
            return ((DescargaDocumentoXML)(results[0]));
        }
        
        /// <remarks/>
        public void DescargaFacturaXMLAsync(string ruc, string user, string password, string documento) {
            this.DescargaFacturaXMLAsync(ruc, user, password, documento, null);
        }
        
        /// <remarks/>
        public void DescargaFacturaXMLAsync(string ruc, string user, string password, string documento, object userState) {
            if ((this.DescargaFacturaXMLOperationCompleted == null)) {
                this.DescargaFacturaXMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDescargaFacturaXMLOperationCompleted);
            }
            this.InvokeAsync("DescargaFacturaXML", new object[] {
                        ruc,
                        user,
                        password,
                        documento}, this.DescargaFacturaXMLOperationCompleted, userState);
        }
        
        private void OnDescargaFacturaXMLOperationCompleted(object arg) {
            if ((this.DescargaFacturaXMLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DescargaFacturaXMLCompleted(this, new DescargaFacturaXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DescargaFacturaPDF", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GetDocument DescargaFacturaPDF(string ruc, string user, string password, string documento) {
            object[] results = this.Invoke("DescargaFacturaPDF", new object[] {
                        ruc,
                        user,
                        password,
                        documento});
            return ((GetDocument)(results[0]));
        }
        
        /// <remarks/>
        public void DescargaFacturaPDFAsync(string ruc, string user, string password, string documento) {
            this.DescargaFacturaPDFAsync(ruc, user, password, documento, null);
        }
        
        /// <remarks/>
        public void DescargaFacturaPDFAsync(string ruc, string user, string password, string documento, object userState) {
            if ((this.DescargaFacturaPDFOperationCompleted == null)) {
                this.DescargaFacturaPDFOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDescargaFacturaPDFOperationCompleted);
            }
            this.InvokeAsync("DescargaFacturaPDF", new object[] {
                        ruc,
                        user,
                        password,
                        documento}, this.DescargaFacturaPDFOperationCompleted, userState);
        }
        
        private void OnDescargaFacturaPDFOperationCompleted(object arg) {
            if ((this.DescargaFacturaPDFCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DescargaFacturaPDFCompleted(this, new DescargaFacturaPDFCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValidaUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UsuarioIntegracion ValidaUsuario(string ruc, string usuario, string password) {
            object[] results = this.Invoke("ValidaUsuario", new object[] {
                        ruc,
                        usuario,
                        password});
            return ((UsuarioIntegracion)(results[0]));
        }
        
        /// <remarks/>
        public void ValidaUsuarioAsync(string ruc, string usuario, string password) {
            this.ValidaUsuarioAsync(ruc, usuario, password, null);
        }
        
        /// <remarks/>
        public void ValidaUsuarioAsync(string ruc, string usuario, string password, object userState) {
            if ((this.ValidaUsuarioOperationCompleted == null)) {
                this.ValidaUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidaUsuarioOperationCompleted);
            }
            this.InvokeAsync("ValidaUsuario", new object[] {
                        ruc,
                        usuario,
                        password}, this.ValidaUsuarioOperationCompleted, userState);
        }
        
        private void OnValidaUsuarioOperationCompleted(object arg) {
            if ((this.ValidaUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidaUsuarioCompleted(this, new ValidaUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EstatusDocumento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EstadoDocumento EstatusDocumento(string ruc, string usuario, string password, string documento) {
            object[] results = this.Invoke("EstatusDocumento", new object[] {
                        ruc,
                        usuario,
                        password,
                        documento});
            return ((EstadoDocumento)(results[0]));
        }
        
        /// <remarks/>
        public void EstatusDocumentoAsync(string ruc, string usuario, string password, string documento) {
            this.EstatusDocumentoAsync(ruc, usuario, password, documento, null);
        }
        
        /// <remarks/>
        public void EstatusDocumentoAsync(string ruc, string usuario, string password, string documento, object userState) {
            if ((this.EstatusDocumentoOperationCompleted == null)) {
                this.EstatusDocumentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEstatusDocumentoOperationCompleted);
            }
            this.InvokeAsync("EstatusDocumento", new object[] {
                        ruc,
                        usuario,
                        password,
                        documento}, this.EstatusDocumentoOperationCompleted, userState);
        }
        
        private void OnEstatusDocumentoOperationCompleted(object arg) {
            if ((this.EstatusDocumentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EstatusDocumentoCompleted(this, new EstatusDocumentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RespuestaTimbradoTXT {
        
        private bool procesadoField;
        
        private string numeroErrorField;
        
        private string mensajeErrorField;
        
        private string nrodeAutorizacionField;
        
        private string fechaHoraField;
        
        private string uUIDField;
        
        private string xMLTimbradoField;
        
        /// <remarks/>
        public bool Procesado {
            get {
                return this.procesadoField;
            }
            set {
                this.procesadoField = value;
            }
        }
        
        /// <remarks/>
        public string NumeroError {
            get {
                return this.numeroErrorField;
            }
            set {
                this.numeroErrorField = value;
            }
        }
        
        /// <remarks/>
        public string MensajeError {
            get {
                return this.mensajeErrorField;
            }
            set {
                this.mensajeErrorField = value;
            }
        }
        
        /// <remarks/>
        public string NrodeAutorizacion {
            get {
                return this.nrodeAutorizacionField;
            }
            set {
                this.nrodeAutorizacionField = value;
            }
        }
        
        /// <remarks/>
        public string FechaHora {
            get {
                return this.fechaHoraField;
            }
            set {
                this.fechaHoraField = value;
            }
        }
        
        /// <remarks/>
        public string UUID {
            get {
                return this.uUIDField;
            }
            set {
                this.uUIDField = value;
            }
        }
        
        /// <remarks/>
        public string XMLTimbrado {
            get {
                return this.xMLTimbradoField;
            }
            set {
                this.xMLTimbradoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EstadoDocumento {
        
        private int codigoField;
        
        private string mensajeField;
        
        /// <remarks/>
        public int codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UsuarioIntegracion {
        
        private string usuarioField;
        
        private string rucField;
        
        private string numErrorField;
        
        private string mensajeField;
        
        /// <remarks/>
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
        
        /// <remarks/>
        public string ruc {
            get {
                return this.rucField;
            }
            set {
                this.rucField = value;
            }
        }
        
        /// <remarks/>
        public string numError {
            get {
                return this.numErrorField;
            }
            set {
                this.numErrorField = value;
            }
        }
        
        /// <remarks/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDocument {
        
        private string codeField;
        
        private string messageField;
        
        private string documentBase64Field;
        
        /// <remarks/>
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string documentBase64 {
            get {
                return this.documentBase64Field;
            }
            set {
                this.documentBase64Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DescargaDocumentoXML {
        
        private string codigoField;
        
        private string mensajeField;
        
        private string documentobase64Field;
        
        /// <remarks/>
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        public string documentobase64 {
            get {
                return this.documentobase64Field;
            }
            set {
                this.documentobase64Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Timbresrestantes {
        
        private bool procesadoField;
        
        private string numeroErrorField;
        
        private string mensajeErrorField;
        
        private string nrodeTicketsField;
        
        /// <remarks/>
        public bool Procesado {
            get {
                return this.procesadoField;
            }
            set {
                this.procesadoField = value;
            }
        }
        
        /// <remarks/>
        public string NumeroError {
            get {
                return this.numeroErrorField;
            }
            set {
                this.numeroErrorField = value;
            }
        }
        
        /// <remarks/>
        public string MensajeError {
            get {
                return this.mensajeErrorField;
            }
            set {
                this.mensajeErrorField = value;
            }
        }
        
        /// <remarks/>
        public string NrodeTickets {
            get {
                return this.nrodeTicketsField;
            }
            set {
                this.nrodeTicketsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RespLoteIntegracion {
        
        private RespuestaTimbradoTXT[] detalleLoteField;
        
        private string codigoField;
        
        private int numdeDocumentosField;
        
        private int correctosField;
        
        private int incorrectosField;
        
        private string mensajeField;
        
        /// <remarks/>
        public RespuestaTimbradoTXT[] detalleLote {
            get {
                return this.detalleLoteField;
            }
            set {
                this.detalleLoteField = value;
            }
        }
        
        /// <remarks/>
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public int numdeDocumentos {
            get {
                return this.numdeDocumentosField;
            }
            set {
                this.numdeDocumentosField = value;
            }
        }
        
        /// <remarks/>
        public int correctos {
            get {
                return this.correctosField;
            }
            set {
                this.correctosField = value;
            }
        }
        
        /// <remarks/>
        public int incorrectos {
            get {
                return this.incorrectosField;
            }
            set {
                this.incorrectosField = value;
            }
        }
        
        /// <remarks/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void FacturaCompletedEventHandler(object sender, FacturaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FacturaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FacturaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RespuestaTimbradoTXT Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RespuestaTimbradoTXT)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void LOTECompletedEventHandler(object sender, LOTECompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LOTECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LOTECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RespLoteIntegracion Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RespLoteIntegracion)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void TimbresRestantesCompletedEventHandler(object sender, TimbresRestantesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TimbresRestantesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TimbresRestantesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Timbresrestantes Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Timbresrestantes)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void DescargaFacturaXMLCompletedEventHandler(object sender, DescargaFacturaXMLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DescargaFacturaXMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DescargaFacturaXMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DescargaDocumentoXML Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DescargaDocumentoXML)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void DescargaFacturaPDFCompletedEventHandler(object sender, DescargaFacturaPDFCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DescargaFacturaPDFCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DescargaFacturaPDFCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetDocument Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetDocument)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ValidaUsuarioCompletedEventHandler(object sender, ValidaUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidaUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidaUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UsuarioIntegracion Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UsuarioIntegracion)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void EstatusDocumentoCompletedEventHandler(object sender, EstatusDocumentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EstatusDocumentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EstatusDocumentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EstadoDocumento Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EstadoDocumento)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591